### ISSUE TITLE
Policies Preserve Ids - Update Docs

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [tractr/directus-sync#101]
**Is your feature request related to a problem? Please describe.**
So when pulling before i added the role ids to be preserved. However i cannot add the policies to be preserved?
```
You can use the --preserve-ids option to preserve the original ids of some collections. Eligible collections are collections using UUID: dashboards, operations, panels, roles and translations. If you have already used the pull command, you may use the untrack helper to remove the id tracking of an element before using this option.
```

**Describe the solution you'd like**
Is it required to add them? Ah nevermind, just saw that it is saved in the permissions object. Maybe add to the docs that they will be automatically tracked and preserved?

**Comment by EdouardDem** [comment]
Thanks, nice catch.
I have fixed it
