### ISSUE TITLE
You don't have permission to access this.

### ISSUE THREAD

**Issue by martijnmichel** [tractr/directus-sync#113]
**Describe the bug**
I am trying to sync our dev to prod envs for the first time.

Did pull from dev, ran diff on prod and finally push on prod instance. However I am getting an error about permissions.

<img width="1337" alt="Screenshot 2024-10-31 at 13 50 06" src="https://github.com/user-attachments/assets/d157f29b-101f-41fa-9aa2-659e0eea6967">

On the instance logs, it says there are no permissions to access /roles

<img width="1381" alt="Screenshot 2024-10-31 at 13 49 06" src="https://github.com/user-attachments/assets/4720dd1b-601f-4320-b826-cedbf0ea83ad">

What am I doing wrong?

**Expected behavior**
Normal sync.

**Versions (please complete the following information):**
 - Directus-Sync version: latest docker image [tractr/directus-sync](https://hub.docker.com/r/tractr/directus-sync).
 - Directus version: latest docker image [tractr/directus-sync](https://hub.docker.com/r/tractr/directus-sync).
 - Directus environment :: both servers are on gcloud run

**Comment by EdouardDem** [comment]
Did you follow [these steps](https://github.com/tractr/directus-sync/blob/main/DOCUMENTATION.md#directus-upgrades) ?

It looks like this one https://github.com/tractr/directus-sync/issues/102

**Comment by martijnmichel** [comment]
I did see that issue but I am not upgrading Directus. They are both fresh installs with the same data structure (through the directus team provided migrate script) but with different data. So users/roles/perms are not the same, and that's exactly what I am trying to achieve.

**Comment by martijnmichel** [comment]
So, I have tested with a new production instance with an exact database copy of the development db. Now, when running pull/diff/push, it works as expected.

Should the initial roles/permissions be the same on both databases for the script to work correctly?

**Comment by EdouardDem** [comment]
Directus creates some default roles and policies. Directus Sync tries to identify them in order to avoid to recreate them.
If those roles and policies are edited, it may lead to the issue you had. More details here : https://github.com/tractr/directus-sync/blob/main/DOCUMENTATION.md#roles--policies

> Roles and policies are tracked.  
> By default, Directus creates a default administrator role and two default policies: _admin_ and _public_.
> 
> 1. To avoid recreating the default _admin_ role, `directus-sync` uses the CLI user's role as the default _admin_ role.
> 2. To avoid recreating the default _public_ policy, `directus-sync` uses the first policy found with `role = null`.
> 3. To avoid recreating the default _admin_ policy, `directus-sync` uses the first policy linked to the _admin_ role with `admin_access = true`.
