### ISSUE TITLE
Migrate from sqlite to mysql

### ISSUE THREAD

**Issue by karamokoisrael** [tractr/directus-sync#15]
Hi, was trying to migrate directus from sqlite to mysql. But I'm facing issues doing that with directus sync. Is there a better way to proceed ?

**Comment by EdouardDem** [comment]
Hi, the database schema is manage by Directus itself, using this feature : https://docs.directus.io/reference/system/schema.html
There is similar issues in the Directus Gituhb : https://github.com/directus/directus/issues/13988
