### ISSUE TITLE
fetch failed: self-signed certificate

### ISSUE THREAD

**Issue by cedenoVF** [tractr/directus-sync#16]
Hi, 

We are using self hosted Directus:

Directus version: 10.8.3
Self hosted:

![image](https://github.com/tractr/directus-sync/assets/85623224/89d8d0e0-6d8e-4b63-8d61-838a527196d9)

To replicate the error run Directus in a self-hosted with a self-signed certificate using HTTPS.

The call "pull" : npx directus-sync pull --config-path './directus-sync.config.cjs'

![image](https://github.com/tractr/directus-sync/assets/85623224/0807b805-2eee-4773-8b2c-9976f63e7026)

The device is in our intranet.. We got our own domain server, so we put the domain directly in the config.

This is our config

Thanks in advance :)

**Comment by EdouardDem** [comment]
Hi @cedenoVF,
You can try to bypass SSL verification by passing environment `NODE_TLS_REJECT_UNAUTHORIZED=0` to Node :

```shell
NODE_TLS_REJECT_UNAUTHORIZED=0 npx directus-sync pull --config-path './directus-sync.config.cjs'
```

**Comment by EdouardDem** [comment]
@cedenoVF I just publish a new version that handles the `./directus-sync.config.cjs` config file path by default.

https://github.com/tractr/directus-sync/pull/24

**Comment by cedenoVF** [comment]
Hi, Thank you for the notification :) noted, We will try later (after we talk about other "issue" )
