### ISSUE TITLE
Creation of collection starting "directus_" will break directus (Schema diff and apply API)

### ISSUE THREAD

**Issue by cedenoVF** [tractr/directus-sync#25]
Directus: V10.8.3
Self hosted

### Behaviour: 
The extension creates a collection starting with "directus_". 

### Problem: 
Those collections are checked by directus system itself and they cant be deleted by the front-end admin panel.
The action will also prevent to use endpoint https://docs.directus.io/reference/system/schema.html#apply-schema-difference 

### suggestion:
use a different name convention in the extension that it does not conflict with "directus_"

**Comment by EdouardDem** [comment]
It's called `directus_sync_id_map` so it can't be deleted or accessed from the front panel.
The loss of certain id mappings will be very damaging.
Schema diff includes the `directus_sync_id_map` collections, but I don't get the issue there.
