### ISSUE TITLE
Can we copy collections schema and data to a different env?

### ISSUE THREAD

**Issue by botzill** [tractr/directus-sync#26]
Can we copy collections schema and data to a different env?

**Comment by EdouardDem** [comment]
Hi @botzill,
Do you mean custom collections ? 
Collections schema are sync with the snapshot process. Custom collections data are not synchronized yet. There is a discussion about it : https://github.com/tractr/directus-sync/issues/1

**Comment by EdouardDem** [comment]
I close this issue because it is duplicated with #1
