### ISSUE TITLE
Sync only specific collections & no snapshot

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [tractr/directus-sync#44]
Is it possible to only sync for example the roles and not other collections ?
And how to not create a snapshot, since having a large database will take long.

**Comment by EdouardDem** [comment]
Unfortunately, there are no options yet to change the snapshot of the database.

However, you can edit the files stored in the `directus-config/snapshot` folder after the `pull` command. You have to delete all collections except for the `directus_sync_id_map.json`.

Create a shell script `clean-snapshot.sh` with the following content:

```bash
#!/usr/bin/env bash

# Remove all JSON files except directus_sync_id_map.json from the collections directory.
find directus-config/snapshot/collections -type f ! -name 'directus_sync_id_map.json' -exec rm {} +

# Remove sub-folders (unless directus_sync_id_map) from the fields directory.
find directus-config/snapshot/fields -mindepth 1 -type d ! -name 'directus_sync_id_map' -exec rm -r {} +

# Remove all subfolders except those related to directus_sync_id_map from the relations directory.
find directus-config/snapshot/relations -mindepth 1 -type d ! -name 'directus_sync_id_map' -exec rm -r {} +
```

Make it executable with `chmod +x clean-snapshot.sh` and run both commands together:

```shell
npx directus-sync pull && ./clean-snapshot.sh
```

Hope this helps!

**Comment by NilsBaumgartner1994** [comment]
It’s because I would like to synchronize for my product the roles and permissions across different instances but well the data itself should be separated.

**Comment by EdouardDem** [comment]
@NilsBaumgartner1994 Thanks for your words!

> to tell which collections and fields i would like to synchronize.

The example above (https://github.com/tractr/directus-sync/issues/44#issuecomment-2057742460) should work for this use case.
You can also exclude (or change) some fields for specific collections :

```javascript
module.exports = {
  hooks: {
    flows: { onDump: () => [] },
    operations: { onDump: () => [] },
    permissions: {
      onDump: (permission) => {
        permission.validation = {};
        delete permission.presets;
        return permission;
      }
    }
    // etc.
  },
};
```

There are [others hooks](https://github.com/tractr/directus-sync?tab=readme-ov-file#hooks) (`onSave`, `onLoad` and `onQuery`) that could help for your case.

**Comment by EdouardDem** [comment]
@NilsBaumgartner1994 
I've just published a new version with features you might be interested in:
- [Snapshot hooks](https://github.com/tractr/directus-sync/tree/directus-sync%401.5.2?tab=readme-ov-file#snapshot-hooks) to edit the snapshot on the fly.
- Ignore snapshot, `excludeCollections` and `onlyCollections` [options](https://github.com/tractr/directus-sync/tree/directus-sync%401.5.2?tab=readme-ov-file#available-options)

You can check the release note: https://github.com/tractr/directus-sync/releases/tag/directus-sync%401.5.2
