### ISSUE TITLE
Support for Public Permissions

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [tractr/directus-sync#64]
Currently only permissions for speicifc roles can be synchronized. Please add a support to also sync the public role permissions.

**Comment by EdouardDem** [comment]
@NilsBaumgartner1994 I have added tests for this use case, but I couldn't reproduce the bug.
Also, on my projects, I have no trouble in syncing public permissions.
Which version of Directus and Directus-Sync do you use ?
