### ISSUE TITLE
Make `directus-extension-sync` compatible with the Directus Marketplace

### ISSUE THREAD

**Issue by EdouardDem** [tractr/directus-sync#67]
https://docs.directus.io/extensions/sandbox/introduction.html

**Comment by EdouardDem** [comment]
Sandboxed extensions does not have access to database yet: https://docs.directus.io/extensions/sandbox/sandbox-sdk.html#reference

**Comment by Loosie94** [comment]
Any indication when this will be added? Would be very handy :)

**Comment by EdouardDem** [comment]
@Loosie94 Unfortunately this is not possible yet due to Directus limitations. Endpoint extensions need to be sandboxed and don't have access to the database.

However you can add this environment variable `MARKETPLACE_TRUST=all` in order to force Directus to list all available extensions: https://docs.directus.io/self-hosted/config-options.html#marketplace
