### ISSUE TITLE
v11 (RC) support

### ISSUE THREAD

**Issue by greenEdgeFranzi** [tractr/directus-sync#87]
**Is your feature request related to a problem? Please describe.**
Pre-release versions for Directus 11 have been published and one of our project's upcoming milestones depends on the new policies feature. We use directus-sync to transfer configurations between staging environments, and we cannot move forward while it is not compatible with the new version. 

**Describe the solution you'd like**
Can you provide an estimated release date for a (pre-release) version with Directus 11 RC support, so we can adapt our schedule accordingly?

**Additional context**
As of today, no official release date has been announced by Directus.

**Comment by EdouardDem** [comment]
@greenEdgeFranzi I will dig into this during August. I will start a new branch for this support. It will likely be a breaking change.

**Comment by Pekket** [comment]
Is there any update on the support of v11?

**Comment by Vahagn-Zaqaryan** [comment]
Hi everyone,

Our team is also using the `directus-sync` module to sync our models between environments, and I just want to extend a huge thank you to everyone involved in working on this module. It has literally saved us months of work and has made our updates so much easier! 🚀

We're eagerly looking forward to the v11 support as well.

Thanks in advance for all your hard work @EdouardDem!

**Comment by EdouardDem** [comment]
Hi @Vahagn-Zaqaryan thanks for your support. I will start working on it this week.

**Comment by Eggwise** [comment]
Yess ! keep up the good work, let us know if there is anything we can do.

**Comment by EdouardDem** [comment]
I have a working version! It was more complicated as expected.
I have to make the tests working. Then I will publish a new version.
Thanks for waiting.

**Comment by mrcjdkhn** [comment]
Hi @EdouardDem, do you have any good news yet?
Please let us know if we can support you in any way.

**Comment by EdouardDem** [comment]
Hi,

Sorry for the delay. It was more complicated as expected. I have a pending
PR. I'm about to merge it and publish.

Le jeu. 5 sept. 2024, 10:23, Marc Jodkuhn ***@***.***> a
écrit :
