### ISSUE TITLE
"Trigger Flow" operation in flows working incorrectly

### ISSUE THREAD

**Issue by scott-lucius-space** [tractr/directus-sync#9]
Of note: currently running Directus v10.2.1

When a flow includes the "Trigger Flow" operation, the flow UUID that it triggers is stored in the "options" field and is not updated causing the flow to become broken.

Example trigger flow in the `operations.json` file:
```
{
    "name": "Trigger Flow",
    "key": "trigger_y2due",
    "type": "trigger",
    "position_x": 48,
    "position_y": 48,
    "options": {
      "flow": "14714bf5-5645-4995-9d2b-8357b98b232d",
      "payload": {
        "data": "{{ $last[0] }}"
      },
      "iterationMode": "serial"
    },
    "resolve": null,
    "reject": null,
    "flow": "b9920111-288b-4200-8b0a-e480ebea19e7",
    "_syncId": "475769af-6e10-48a9-8e2e-83cc625e8686"
  },
```

I may not fully understand how the linking is working in directus-sync but that 14714bf5 flow ID is also the _syncId of the first operation in the flow that is triggered as well as the (as expected) "operation" field in the triggered flow in the flows.json file.

Per [this](https://github.com/tractr/directus-sync/blob/10d3c0e1cf7a968f86bb4ffe511e7feb2a0694a5/packages/cli/src/lib/services/collections/flows/collection.ts#L41), it seems like maybe the trigger flow operations are just not getting updated with the newly created triggered flow UUID after creation?

Happy to submit a PR after a bit more understanding of how this linking is working. Would there just need to be a check for flow being a key under options before this [idMappers](https://github.com/tractr/directus-sync/blob/10d3c0e1cf7a968f86bb4ffe511e7feb2a0694a5/packages/cli/src/lib/services/collections/operations/data-mapper.ts#L17) object and then updating it beforehand?

**Comment by EdouardDem** [comment]
@scott-lucius-space Relation fields are replace by `_syncId` and vice-versa during the `pull` and the `push` processes.
I just noticed today that the `options.flow` is not replaced. I had the same issue you have on a project.
I'm working on a fix. I can send you the PR if you want to see how the id replacement is done.

**Comment by EdouardDem** [comment]
Here it is: https://github.com/tractr/directus-sync/pull/10

**Comment by scott-lucius-space** [comment]
Hmmmm unless I'm doing something wrong I'm still running into issues. Pulled from main branch and built cli package fresh. The options.flow on Trigger Flows have UUIDs but I don't see them referenced anywhere else in directus-config. Will dig in a bit more to make sure it's not a mistake on my end.

**Comment by EdouardDem** [comment]
> I think they should have been converted to the _syncIds for the flows on the `directus-sync pull` right?

Yes that's it. Real flow ids are changed to `_syncIds` on `directus-sync pull` then `_syncIds` are changed back to real ids on `directus-sync push`.
Therefore, in `directus-config/operations.json`, `options.flow` should the `_syncId` of one of the items in `directus-config/flows.json`.

I will check again on my side too.

**Comment by scott-lucius-space** [comment]
I'm an idiot -- my mistake -- I was using `npx directus-sync ...` for the pull and then the freshly built with changes for the push. It appears correct now just from cursory glance -- will test here in a minute.

**Comment by scott-lucius-space** [comment]
Tested and everything is working great!! Thanks so much again @EdouardDem!
