### ISSUE TITLE
Error When Syncing New Folders Between Environments: "Value for field 'id' in collection 'directus_folders' has to be unique."

### ISSUE THREAD

**Issue by Vahagn-Zaqaryan** [tractr/directus-sync#92]
## Describe the Bug
I maintain both production and testing environments, and our content writers recently organized our media files into folders. When I first attempted to sync these folders between environments, everything worked smoothly. However, after they created a few additional folders, I encountered an error: `Value for field "id" in collection "directus_folders" has to be unique.`

## To Reproduce
Steps to reproduce the issue:
1. Set up two empty Directus instances.
2. Create a folder in one of the instances.
3. Sync the folder to the other instance.
4. Create another folder.
5. Attempt to sync the second folder, and you should encounter the following error:

```shell
ERROR (1918487):
    errors: [
      {
        "message": "Value for field \"id\" in collection \"directus_folders\" has to be unique.",
        "extensions": {
          "collection": "directus_folders",
          "field": "id",
          "code": "RECORD_NOT_UNIQUE"
        }
      }
    ]
    response: {}
```

## Expected Behavior
The synchronization should complete without any issues.

## Versions
- **Directus-Sync Version**: 2.2.0
- **Directus Version**: 10.13.2
- **Environment**: Docker/Self-hosted

## Additional Context
First, I want to express my gratitude for creating and maintaining this repository. It has saved us months of work, and I'm eager to assist in making it even better! 🚀

If you need any further information, please don't hesitate to ask.

**Comment by NilsBaumgartner1994** [comment]
Having hte same bug

**Comment by NilsBaumgartner1994** [comment]
Our workaround was to ```pull``` from the server, then discard other wrong pulled informations, then pushed back.

**Comment by EdouardDem** [comment]
@Vahagn-Zaqaryan Thank you for your words.
I will dive into this issue. 
When you say `Create another folder.`, is it a standalone folder or is it a subfolder of the first one ?
