### ISSUE TITLE
Folder Creation Issue During Push Command

### ISSUE THREAD

**Issue by khanahmad4527** [tractr/directus-sync#99]
**Describe the bug**
When setting the default storage folder location and running the directus-sync push command, it fails because the necessary folders haven’t been created yet. This requires running the push command twice, first excluding the directus_settings collection to create the folders, and then running the push command again to include all collections.

**To Reproduce**
1. Set the default storage folder location in Directus
2. run the pull cmd
3. run the push cmd
```bash
npx directus-sync --directus-url http://localhost:8055 --directus-email admin@example.com --directus-password xxxxxxxx push --preserve-ids all 
```

**Expected behavior**
The default folder setting should be updated in the Directus settings options without requiring multiple push commands.

**Versions (please complete the following information):**
 - Directus-Sync version: [e.g. 3.1.2]
 - Directus version: [e.g. 11.1.0]
 - Directus environment [Self-hosted]

**Additional context**
Make sure that a folder exits in the Directus and that folder is getting used as a default storage folder
![image](https://github.com/user-attachments/assets/83ec2adb-ace6-46d7-ae6f-997533372811)
![image (1)](https://github.com/user-attachments/assets/e83af1f7-2b40-40f2-b4f7-b5c1f839c2fb)

**Comment by EdouardDem** [comment]
@khanahmad4527 This has been fixed: https://github.com/tractr/directus-sync/releases/tag/directus-sync%403.1.3
